my-image:
  stage: build
  image: kdungs/clafoutis:latest
  tags:
    - privileged
  script:
    - clafoutis --zip
      --distdir $CI_PROJECT_DIR/dist
      --name clafoutis-example
  artifacts:
    paths:
      - /clafoutis-example.zip
    expire_in: 1 day
